[[modeling-workbench-executing-model-section]]
=== Executing model
==== Launch configuration

The Gemoc launch configuration offers both a Run and a Debug mode.

===== Run mode
In run mode, it offers the faster way to run the model.
It cannot be paused. However you can stop it.
It offers a limited set of views
	- deactivate views
		- logical steps
		- event manager
		- timeline
===== Debug mode
In debug mode, the engine offers more control on the execution.
It allows to pause, add break point,


	- activate layer debug
	- activate layer animation
	- show EMF tree in variables view

===== Backends and frontends
Back ends and front ends offer additionnal view that can respectivly display informations from the running model or provide event input to the running model.

These backends and front ends usually open dedicated views. These views are always opened in all modes (Run or Debug).

==== Engine view

==== Logical step view

==== Event manager view

==== Animation view
