= GEMOC Studio Guide
Francois Tanguy <francois.tanguy@inria.fr>, Didier Vojtisek <didier.vojtisek@inria.fr>
:doctype: book
:toc:
:numbered:

////////////////////////////////////////////////////////////////
[dedication]
== Dedication

TBD
////////////////////////////////////////////////////////////////

[preface]
== Introduction

The GEMOC Studio offers 2 main usages: 

* Building and composing new executable DSML. This mode is intended to be used by language designers (aka domain experts).

* Creating and executing models conformant to executable DSMLs. This mode is intended to be used by domain designers.

Each of these usage has it own set of tools that are referenced as *Gemoc Language workbench* for the tools for _language designers_ and *Gemoc Modeling Workbench* for the tools for _domain designers_.

include::GuideLanguageWorkbenchChapter.asciidoc[]

include::GuideModelingWorkbenchChapter.asciidoc[]

:numbered!:

////////////////////////////////////////////////////////////////
[appendix]
== Example Appendix

One or more optional appendixes go here at section level 1.

=== Appendix Sub-section

Sub-section body.
////////////////////////////////////////////////////////////////

include::GuideBibliography.asciidoc[]

include::GuideGlossary.asciidoc[]

////////////////////////////////////////////////////////////////
[colophon]
== Example Colophon

Text at the end of a book describing facts about its production.
////////////////////////////////////////////////////////////////

[index]
== Index
////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
