[[modeling-workbench-executing-model-section]]
=== Executing model
==== Launch configuration

The Gemoc launch configuration offers both a Run and a Debug mode.

===== General options
- Model to execute : this is the model that will be run
- xDSML : this field allows to select among the valid variants of the executable language that are available for the model (Ie. the combinaison of DSA, DSE and MoCC that can be used on the given domain model)
- ((Decider)) : this field allows to select the solver strategy used by the engine when several ((Logical Step))s can be triggered. Possible choice are : 
** Solver proposition : the solver internal stategy will be used to selecton Logical Step
** Random : will randomly select one of the available Logical Step (warning: execution cannot be reproduced when using this Decider)
** Ask user : (available only in Debug mode), this option will use the <<modeling-workbench-executing-model-logical-step-view-section,Logical Step View>> or the <<modeling-workbench-executing-model-timeline-view-section,Timeline View>> to present the available Logical Steps and pause if there are more than one Logical Step. The user will then need to click on one of the Logical Step to continue.
** Ask user (Step by step) : (available only in Debug mode), this option is similar to the previous one. However, it will pause on every Logical Step, even if there is only one Logical Step that can be triggered.

More Deciders will be developped (for example for playing predefined scenario).

===== Run mode
In run mode, it offers the faster way to run the model.
It cannot be paused. However, you can stop it.
It offers a limited set of views:
* the <<modeling-workbench-executing-model-engine-view-section,((Engine View))>> allows to stop a running model.
* the <<modeling-workbench-executing-model-timeline-view-section,((Timeline view))>> is displayed at the end of the execution in order to control the resulting execution trace.

If more feed back are required, please use one of the front end or back end available for the xDSML. 

===== Debug mode
In debug mode, the engine offers more control on the execution.
It allows to pause, add break point, and run in a step by step mode.

If offers several views.

logical steps
		- event manager
		- timeline

	- activate layer debug
	- activate layer animation
	- show EMF tree in variables view

===== Backends and frontends
Back ends and front ends offer additionnal view that can respectivly display informations from the running model or provide event input to the running model.

These backends and front ends usually open dedicated views. These views are always opened in all modes (Run or Debug).


[[modeling-workbench-executing-model-engine-view-section]]
==== Engine View

[[modeling-workbench-executing-model-logical-step-view-section]]
==== Logical Step View

[[modeling-workbench-executing-model-timeline-view-section]]
==== Timeline View


==== Event Manager View

==== Animation View
