////
ifeval::[{docname}=='TutorialMain']
:toc:
:numbered:
:tabsize=4:
endif::[]
////


= GEMOC xDSML tutorial



The purpose of these tutorials is to explain on simple examples with
different features, how to define an eXecutable Domain Specific Modeling
Language (xDSML). Based on an existing DSML definition (abstract and concrete
syntaxes), we define a concurrent semantics.




- link:../../tutorial_markedgraph/html_single/GuideTutorialMarkedGraph.html[Marked Graph tutorial] (or link:../../tutorial_markedgraph/html/GuideTutorialMarkedGraph.html[chunked version]): quick example to
  demonstrate how to define an
  execution semantics and graphical animation for a highly concurrent language,
  Marked Graph.

- link:../../tutorial_sigpml/html_single/Tutorial_SigPML.html[SigPML tutorial] (or link:../../tutorial_sigpml/html/Tutorial_SigPML.html[chunked version])

////

- link:../../tutorial_automata/html_single/Tutorial_Automata.html[Automata tutorial] (or link:../../tutorial_automata/html/Tutorial_Automata.html[chunked version]): The used DSML is automata
  used to recognize words built on an alphabet.   Its focus is on a possible
  methodology to make a DSML executable.

////
